version: "2"

services:
  notebook:
    build: .
    ports:
      - 8888:8888
    hostname: ${USER}-notebook
    user: root
    environment:
      GRANT_SUDO: 'yes'
      NB_UID: ${NB_UID}
    volumes:
      - .:/home/jovyan/metaprob:rw
